services:

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - staging.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vod_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vod_password}
      POSTGRES_DB: ${POSTGRES_DB:-vod_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
    networks:
      - backend_net_staging


  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console UI
    env_file:
      - staging.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - minio_data_staging:/data
    command: server /data --console-address ":9001"
    networks:
      - backend_net_staging  

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - staging.env
    ports:
      - "6379:6379"      # host : container
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD"

    networks:
      - backend_net_staging
    
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_dev_password", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3



  api:
    cpu_shares: 1024
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - staging.env
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "127.0.0.1:8001:8000"
    networks:
      - backend_net_staging
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]



  worker:
    cpu_shares: 256
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - staging.env
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - backend_net_staging
    command: ["celery", "-A", "app.celery_app:celery_app", "worker", "--loglevel=INFO", "--concurrency=2"]


networks:
  backend_net_staging:
    driver: bridge

volumes:
  postgres_data_staging:
  minio_data_staging:
    driver: local
