version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: vod_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vod_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vod_password}
      POSTGRES_DB: ${POSTGRES_DB:-vod_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: vod_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend_net
    volumes:
      - pgadmin_data:/var/lib/pgadmin 

  minio:
    image: minio/minio:latest
    container_name: vod_minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - backend_net  # Changed from vod_network to backend_net
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]  # Better healthcheck
      interval: 30s
      timeout: 20s
      retries: 3


  redis:
    image: redis:7-alpine
    container_name: vod_redis
    restart: unless-stopped
    ports:
      - "6379:6379"      # host : container
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis_dev_password}
    
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD"

    networks:
      - backend_net
    
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_dev_password", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3


  redisinsight:
    image: redis/redisinsight:latest
    container_name: vod_redis_insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    networks:
      - backend_net
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/data



networks:
  backend_net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  minio_data:
    driver: local
  redisinsight_data: