version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: vod_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vod_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vod_password}
      POSTGRES_DB: ${POSTGRES_DB:-vod_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: vod_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend_net
    volumes:
      - pgadmin_data:/var/lib/pgadmin 

  # app:
  #   build: ../backend
  #   depends_on:
  #     - db
  #   networks:
  #     - backend_net
  #   environment:
  #     DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

networks:
  backend_net:

volumes:
  postgres_data:
  pgadmin_data:
